# Generated by Django 3.2.6 on 2021-08-11 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('preco', models.FloatField()),
                ('rendimento', models.TextField(max_length=100)),
                ('categria', models.CharField(max_length=100)),
                ('date_prato', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
