# Generated by Django 3.2.6 on 2021-08-17 16:39

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prato',
            old_name='categria',
            new_name='categoria',
        ),
    ]
