# Generated by Django 3.2.6 on 2021-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_prato_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
