# Generated by Django 3.2.6 on 2021-08-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_prato_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='foto_prato',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
