# Generated by Django 3.2.6 on 2021-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_alter_prato_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='preco',
            field=models.CharField(max_length=100),
        ),
    ]
